FROM golang:1.22 AS build-stage

WORKDIR /home

COPY go.mod go.sum ./
RUN go mod download

COPY pb/ ./pb
COPY main.go ./

RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o server main.go

FROM gcr.io/distroless/base:latest AS final-stage

WORKDIR /usr/local/bin

COPY --from=build-stage /home/server ./

CMD [ "./server" ]

